### ISSUE TITLE
LoadError: cannot load such file lib/core_ext/object

### ISSUE THREAD

**Issue by nderkach** [flyiin/ndc-ruby-sdk#1]
Hi,

after building and installing the gem from a gemespec provided in repository, I get the following error:

```
LoadError: cannot load such file -- /usr/local/lib/ruby/gems/2.2.0/gems/ndc-client-0.0.1/lib/core_ext/object
```

**Comment by xurde** [comment]
How did you installed the resulting gem?

My suggestion is that you bundle it straight from the repo adding this to your app's Gemfile.
`gem "ndc-client", :git => 'https://github.com/flyiin/ndc-ruby-sdk'`

And then just run `bundle install`

**Comment by nderkach** [comment]
That's exactly what'm doing. I'm using the gateway project to test the gem.
How to reproduce:
1. git clone https://github.com/nderkach/ndc-ruby-gateway (I only change it to use github gem instead of the local one)
2. bundle install
3. rake test

UPD: seems like some files are missing after instilling the gem:

``` sh
$ ls /usr/local/lib/ruby/gems/2.2.0/gems/ndc-client-0.0.1/lib/
ndc-client.rb
```

**Comment by xurde** [comment]
No, but you should use this gem in your own project rather than using the gateway.
The NDC gateway became outdated with the latest version of the SDK. On top of that it requires configuration files to access NDC services which obviously are not published in the code, since you need to be approved by an NDC provider and customize wrapping settings.

Create a new Rails app for instance, and add this line in your Gemfile
`gem "ndc-client", :git => 'https://github.com/flyiin/ndc-ruby-sdk'`

Starting on this, follow the SDK instructions to build requests. You still will need to be granted access to a certified NDC provider.

**Comment by nderkach** [comment]
I see. There still seems to be the problem with some missing files:

``` ruby
irb(main):001:0> require 'ndc-client'
LoadError: cannot load such file -- /usr/local/lib/ruby/gems/2.2.0/gems/ndc-client-0.0.1/lib/version
    from /usr/local/lib/ruby/gems/2.2.0/gems/ndc-client-0.0.1/lib/ndc-client.rb:10:in `require_relative'
    from /usr/local/lib/ruby/gems/2.2.0/gems/ndc-client-0.0.1/lib/ndc-client.rb:10:in `<top (required)>'
    from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
    from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
    from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
    from (irb):1
    from /usr/local/bin/irb:11:in `<main>'
```

UPD: PR below seems to fix the issue.

**Comment by xurde** [comment]
See. I followed this steps:
1. `git clone git@github.com:flyiin/ndc-ruby-sdk.git`
2. `ndc-ruby-sdk`
3. `bundle`
4. `bundle exec irb`

Once in the IRB env:

```
require 'ndc-client'
=> true
```

Can you try this please?
